---
- name: Controller Basic - Check for towalink-tlm directory
  local_action: stat path={{ tlm_path }}
  register: stat_dir_tlm

- name: Controller Basic - Install required packages (apk)
  apk:
    name:
      - rsync
      - ansible
      - py3-pip
      - py3-virtualenv
      - wireguard-tools
    state: present
  tags: installation
  when: ansible_facts['os_family'] == 'Alpine'

- name: Controller Basic - Install required packages (apt)
  apt:
    name:
      - rsync
      - ansible
      - python3-pip
      - python3-venv
#      - python3-virtualenv
    state: present
  tags: installation
  when: ansible_facts['os_family'] == 'Debian'

- name: Controller Basic - Add Debian Buster backports repository
  apt_repository:
    repo: deb http://http.debian.net/debian buster-backports main contrib
    state: present
    update_cache: yes  
  tags: installation
  when: (ansible_facts['os_family'] == 'Debian') and (ansible_facts['distribution_release'] == 'buster')

- name: Controller Basic - Install Wireguard (apt)
  apt:
    name:
      - wireguard
      - "linux-headers-{{ ansible_kernel }}"
      - wireguard-dkms
    state: present
    default_release: "{{ 'buster-backports' if (ansible_facts['distribution_release'] == 'buster') else omit }}" 
  tags: installation
  when: ansible_facts['os_family'] == 'Debian'

- name: Controller Basic - Install Towalink tlm Python module
  pip:
    name:
      - towalink-tlm
    state: present
    virtualenv: "{{ python_venv or omit }}"
    virtualenv_command: /usr/bin/python3 -m venv
    virtualenv_site_packages: yes # needed so that module "cryptography" does not need to be compiled
  tags: installation
  when: not stat_dir_tlm.stat.exists

- name: Controller Basic - Install locally available Towalink tlm Python module
  pip: name={{ tlm_path }}
       extra_args='-e'
       virtualenv="{{ python_venv or omit }}"
       virtualenv_site_packages=yes
  when: stat_dir_tlm.stat.exists
